# Generated by Django 5.0.1 on 2024-02-07 18:27

import django.db.models.deletion
import face_recognition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=face_recognition.models.getUploadPath)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition.person')),
            ],
        ),
    ]
